pipeline{
  agent any

  stages{
    
    stage('Checkout') {
      steps{
        checkout scm
      }
    }

    stage('Flutter Doctor') {
      steps{
        sh 'flutter doctor'
      }
    }

    stage('Get Packages') {
      steps{
        sh 'flutter pub get'
      }
    }

    stage('Analyze') {
      steps{
        sh 'flutter analyze'
      }
    }

    stage('Trigger APK Build') {
      steps{
        echo "GitHub Actions will build APK" 
      }
    }
    
  }

  post{
    success{
      echo "Pipeline Passed"
    }

    failure{
      echo "Pipeline Failed"
    }
  }
}
